version: '3'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: book-review-postgis-db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: book-review-redis
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data:/var/lib/redis